version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3.8.1-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  postgresdb:
    image: postgres:12.0
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: clew_medical
      POSTGRES_PASSWORD: password
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  consumer:
    command: tail -f /dev/null
    build:
      context: ./ConsumerService
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: admin
      POSTGRES_DB: clew_medical
      POSTGRES_PASSWORD: password
    volumes:
      - .:/deploy
    depends_on:
      - rabbitmq
      - postgresdb

  publisher:
    command: tail -f /dev/null
    build:
      context: ./PublisherService
    depends_on:
      - rabbitmq
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_USER: admin
      RABBIT_PASS: password

